name: CI-CD Template

on:
  workflow_call:
    inputs:
      java_version:
        required: true
        type: string
      gradle_version:
        required: true
        type: string
    secrets:
      GH_PACKAGES_USER:
        required: true
      GH_PACKAGES_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: danielgalvezpilco/gh-actions-library/.github/actions/setup-java@main
        with:
          java_version: ${{ inputs.java_version }}

      - name: Build with Gradle
        run: ./gradlew build
