name: CI-CD Template

on:
  workflow_call:
    inputs:
      java_version:
        required: true
        type: string
      gradle_version:
        required: true
        type: string
      registry_name:
        required: true
        type: string
      azure_tenant_id:
        required: true
        type: string
      azure_subscription_id:
        required: true
        type: string
      resource_group:
        required: true
        type: string
      cluster_name:
        required: true
        type: string
      profile:
        required: true
        type: string
      cluster_namespace:
        required: true
        type: string
      cluster_max_replica:
        required: true
        type: string
      cluster_min_replica:
        required: true
        type: string
    secrets:
      GH_PACKAGES_USER:
        required: true
      GH_PACKAGES_TOKEN:
        required: true
      AZURE_CLIENT_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: danielgalvezpilco/gh-actions-library/java/deploy@main
        with:
          java_version: ${{ inputs.java_version }}
          gradle_version: ${{ inputs.gradle_version }}
          registry_name: ${{ inputs.registry_name }}
          azure_tenant_id: ${{ inputs.azure_tenant_id }}
          azure_subscription_id: ${{ inputs.azure_subscription_id }}
          resource_group: ${{ inputs.resource_group }}
          cluster_name: ${{ inputs.cluster_name }}
          profile: ${{ inputs.profile }}
          cluster_namespace: ${{ inputs.cluster_namespace }}
          cluster_max_replica: ${{ inputs.cluster_max_replica }}
          cluster_min_replica: ${{ inputs.cluster_min_replica }}
        secrets:
          GH_PACKAGES_USER: ${{ secrets.GH_PACKAGES_USER }}
          GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
